export const portfolioData = [
  {
    id: 1,
    logo: "https://rdlcom.com/wp-content/uploads/qa-testing-as-a-service-test-io-creative-company-logo-terrific-1.png",
    title: "Lorem Ipsum one",
    desc: "Lorem Ipsum dolor sit amet",
    color: "#F5F5F4",
    font_color: "#0EA5E9",
    alphabet: "A",
    url: "http://google.com",
  },
  {
    id: 2,
    logo: "https://rdlcom.com/wp-content/uploads/qa-testing-as-a-service-test-io-creative-company-logo-terrific-1.png",
    title: "Lorem Ipsum two",
    desc: "Lorem Ipsum dolor sit amet",
    color: "#A5F3FC",
    font_color: "#6B21A8",
    alphabet: "A",
    url: "http://google.com",
  },
  {
    id: 3,
    logo: "https://rdlcom.com/wp-content/uploads/qa-testing-as-a-service-test-io-creative-company-logo-terrific-1.png",
    title: "Lorem Ipsum",
    desc: "Lorem Ipsum dolor sit amet",
    color: "#6B21A8",
    font_color: "#fff",
    alphabet: "B",
    url: "http://google.com",
  },
  {
    id: 4,
    logo: "https://rdlcom.com/wp-content/uploads/qa-testing-as-a-service-test-io-creative-company-logo-terrific-1.png",
    title: "Lorem Ipsum",
    desc: "Lorem Ipsum dolor sit amet",
    color: "#E11D48",
    font_color: "#fff",
    alphabet: "C",
    url: "http://google.com",
  },
  {
    id: 5,
    logo: "https://rdlcom.com/wp-content/uploads/qa-testing-as-a-service-test-io-creative-company-logo-terrific-1.png",
    title: "Lorem Ipsum",
    desc: "Lorem Ipsum dolor sit amet",
    color: "#FDA4AF",
    font_color: "#000",
    alphabet: "D",
    url: "http://google.com",
  },
  {
    id: 6,
    logo: "https://rdlcom.com/wp-content/uploads/qa-testing-as-a-service-test-io-creative-company-logo-terrific-1.png",
    title: "Lorem Ipsum",
    desc: "Lorem Ipsum dolor sit amet",
    color: "#FDE68A",
    font_color: "#000",
    alphabet: "W",
    url: "http://google.com",
  },
];
